global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tinyurl-monitor'

rule_files:
  - 'tinyurl_rules.yml'

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # TinyURL 應用程式監控
  - job_name: 'tinyurl-api'
    static_configs:
      - targets: ['tinyurl-api:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 3s

  # PostgreSQL 監控（透過 postgres_exporter，可選）
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis 監控（透過 redis_exporter，可選）
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

# 告警規則配置（可選）
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
