spring:
  # 測試環境資料庫配置（使用 H2 記憶體資料庫）
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  # 測試環境 JPA 配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # 禁用 Flyway（測試使用 create-drop）
  flyway:
    enabled: false

  # 測試環境 Redis 配置（將使用 Testcontainers）
  data:
    redis:
      host: localhost
      port: 6379

# 測試環境日誌配置
logging:
  level:
    '[com.example.tinyurl]': DEBUG
    '[org.springframework.test]': INFO
    '[org.testcontainers]': INFO
    '[org.hibernate.SQL]': DEBUG

# 關閉管理端點（測試環境不需要）
management:
  endpoints:
    enabled-by-default: false
