# 生產環境配置
spring:
  # 生產環境資料庫配置（優化）
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  # 生產環境 JPA 配置
  jpa:
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
        '[use_sql_comments]': false
        jdbc:
          '[batch_size]': 25
        '[order_inserts]': true
        '[order_updates]': true

  # 生產環境 Redis 配置
  data:
    redis:
      timeout: 5000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

# 生產環境日誌配置（JSON 格式）
logging:
  level:
    '[com.example.tinyurl]': INFO
    '[org.springframework.web]': WARN
    '[org.hibernate.SQL]': WARN
    root: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 生產環境監控配置
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true
    db:
      enabled: true

# 生產環境伺服器配置
server:
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful

# 生產環境關閉 Swagger UI
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
